//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPatcher.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPatcher.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize application from {0} due to error:
        ///    
        ///{1}
        ///    
        ///Please correct the configuration error, or delete the configuration file and restart to generate a new template..
        /// </summary>
        internal static string StringConfigurationLoadFailure {
            get {
                return ResourceManager.GetString("StringConfigurationLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write configuration to {0} due to error:
        ///
        ///{1}
        ///    .
        /// </summary>
        internal static string StringConfigurationWriteFailure {
            get {
                return ResourceManager.GetString("StringConfigurationWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform operation due to error: {0}.
        /// </summary>
        internal static string StringFailureGeneral {
            get {
                return ResourceManager.GetString("StringFailureGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform operation due to invalid Local Binaries Root path {0}..
        /// </summary>
        internal static string StringFailureInvalidLocalBinRoot {
            get {
                return ResourceManager.GetString("StringFailureInvalidLocalBinRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform operation due to invalid Remote Binaries Root path {0}..
        /// </summary>
        internal static string StringFailureInvalidRemoteBinRoot {
            get {
                return ResourceManager.GetString("StringFailureInvalidRemoteBinRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform operation due to invalid Source Items Root path {0}..
        /// </summary>
        internal static string StringFailureInvalidSourceItemsRoot {
            get {
                return ResourceManager.GetString("StringFailureInvalidSourceItemsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to patch file {0} due to error:
        ///    
        ///{1}.
        /// </summary>
        internal static string StringPatchFailureGeneral {
            get {
                return ResourceManager.GetString("StringPatchFailureGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmapped Source Item: {0}.
        /// </summary>
        internal static string StringUnmappedFile {
            get {
                return ResourceManager.GetString("StringUnmappedFile", resourceCulture);
            }
        }
    }
}
