//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string StringAboutContent {
            get {
                return ResourceManager.GetString("StringAboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPatcher, by Christian Gunderman.
        /// </summary>
        public static string StringAboutMessage {
            get {
                return ResourceManager.GetString("StringAboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string StringAddContent {
            get {
                return ResourceManager.GetString("StringAddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Artifacts.
        /// </summary>
        public static string StringBuildArtifactsContent {
            get {
                return ResourceManager.GetString("StringBuildArtifactsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StringCancelContent {
            get {
                return ResourceManager.GetString("StringCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Repo.
        /// </summary>
        public static string StringCloseRepoContent {
            get {
                return ResourceManager.GetString("StringCloseRepoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string StringConfigurationContent {
            get {
                return ResourceManager.GetString("StringConfigurationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize application from {0} due to error:
        ///    
        ///{1}
        ///    
        ///Please correct the configuration error, or delete the configuration file and restart to generate a new template..
        /// </summary>
        public static string StringConfigurationLoadFailure {
            get {
                return ResourceManager.GetString("StringConfigurationLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write configuration to {0} due to error:
        ///
        ///{1}
        ///    .
        /// </summary>
        public static string StringConfigurationWriteFailure {
            get {
                return ResourceManager.GetString("StringConfigurationWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string StringEditContent {
            get {
                return ResourceManager.GetString("StringEditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patch Scheme.
        /// </summary>
        public static string StringEditPatchSchemeContent {
            get {
                return ResourceManager.GetString("StringEditPatchSchemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPatcher Error.
        /// </summary>
        public static string StringErrorDialogTitle {
            get {
                return ResourceManager.GetString("StringErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string StringExitContent {
            get {
                return ResourceManager.GetString("StringExitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string StringFileContent {
            get {
                return ResourceManager.GetString("StringFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string StringHelpContent {
            get {
                return ResourceManager.GetString("StringHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPatcher Information.
        /// </summary>
        public static string StringInformationDialogTitle {
            get {
                return ResourceManager.GetString("StringInformationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPatcher.
        /// </summary>
        public static string StringMainWindowTitle {
            get {
                return ResourceManager.GetString("StringMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Repo.
        /// </summary>
        public static string StringNewRepoContent {
            get {
                return ResourceManager.GetString("StringNewRepoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Repo Configuration.
        /// </summary>
        public static string StringNewRepoDialogTitle {
            get {
                return ResourceManager.GetString("StringNewRepoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string StringOkContent {
            get {
                return ResourceManager.GetString("StringOkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Repo.
        /// </summary>
        public static string StringOpenRepoContent {
            get {
                return ResourceManager.GetString("StringOpenRepoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Repo Configuration.
        /// </summary>
        public static string StringOpenRepoDialogTitle {
            get {
                return ResourceManager.GetString("StringOpenRepoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPatcher Editor.
        /// </summary>
        public static string StringPatchEditorTitle {
            get {
                return ResourceManager.GetString("StringPatchEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string StringRemoveContent {
            get {
                return ResourceManager.GetString("StringRemoveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create configuration file. File name must be {0}..
        /// </summary>
        public static string StringRepoNewInvalidFileName {
            get {
                return ResourceManager.GetString("StringRepoNewInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo Path: .
        /// </summary>
        public static string StringRepoPathLabelContent {
            get {
                return ResourceManager.GetString("StringRepoPathLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repo loaded.
        /// </summary>
        public static string StringRepoPathNoneContent {
            get {
                return ResourceManager.GetString("StringRepoPathNoneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Items.
        /// </summary>
        public static string StringSourceItemsContent {
            get {
                return ResourceManager.GetString("StringSourceItemsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StringStatusBarReady {
            get {
                return ResourceManager.GetString("StringStatusBarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string StringStatusBarWorking {
            get {
                return ResourceManager.GetString("StringStatusBarWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPatcher Warning.
        /// </summary>
        public static string StringWarningDialogTitle {
            get {
                return ResourceManager.GetString("StringWarningDialogTitle", resourceCulture);
            }
        }
    }
}
